# Generated by Django 5.0.7 on 2024-11-14 09:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_long_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
