# Generated by Django 5.0.7 on 2024-08-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleproduct',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
