# Generated by Django 5.0.7 on 2024-11-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_for',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Boy', 'Boy'), ('Girl', 'Girl')], default='Men', max_length=255, null=True),
        ),
    ]
