# Generated by Django 5.0.7 on 2024-08-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_simpleproduct_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleproduct',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='simpleproduct',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
