# Generated by Django 5.0.7 on 2024-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productreview_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleproduct',
            name='flat_delivery_fee',
        ),
        migrations.RemoveField(
            model_name='simpleproduct',
            name='virtual_product',
        ),
        migrations.AddField(
            model_name='products',
            name='flat_delivery_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='virtual_product',
            field=models.BooleanField(default=False),
        ),
    ]
