# Generated by Django 5.0.7 on 2024-08-31 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variations', '0002_variant_remove_productvariation_parent_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('video', models.JSONField(blank=True, default=list, null=True)),
                ('variant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gallery', to='product_variations.variantproduct')),
            ],
        ),
    ]
