# Generated by Django 5.0.7 on 2024-09-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variations', '0003_variantimagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantproduct',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
