# Generated by Django 5.0.7 on 2024-11-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('callback_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
