# Generated by Django 5.0.7 on 2024-08-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the banner')),
                ('active', models.BooleanField(default=True, help_text='Only active banners will be displayed')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
