# Generated by Django 5.0.7 on 2024-11-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
