# Generated by Django 5.0.7 on 2024-09-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_applied_coupon_alter_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
