# Generated by Django 5.0.7 on 2024-08-30 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.JSONField(blank=True, default=dict, null=True)),
                ('product_info', models.JSONField(blank=True, default=dict, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
